---
ansible_connection: local
openshift_cluster_content:
- object: ci-cd-tooling
  content:
  - name: "nexus"
    namespace: "{{ ci_cd_namespace }}"
    template: "{{ playbook_dir }}/templates/nexus.yml"
    params: "{{ playbook_dir }}/params/nexus"
    tags:
    - nexus
  - name: "jenkins"
    namespace: "{{ ci_cd_namespace }}"
    template: "{{ playbook_dir }}/templates/jenkins.yml"
    params: "{{ playbook_dir }}/params/jenkins"
    tags:
    - jenkins
  - name: "gitlab"
    namespace: "{{ ci_cd_namespace }}"
    template: "{{ playbook_dir }}/templates/gitlab.yml"
    params: "{{ playbook_dir }}/params/gitlab"
    tags:
    - gitlab
  - name: "jenkins-mongodb"
    namespace: "{{ ci_cd_namespace }}"
    template: "{{ playbook_dir }}/templates/mongodb.yml"
    params: "{{ playbook_dir }}/params/mongodb"
    tags:
    - mongodb
