---
apiVersion: v1
kind: Template
metatdata:
  creationTimestamp: null
  name: gitlab.template
objects:
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: gitlab
    labels:
      app: gitlab
      name: gitlab
  spec:
    host: gitlab-jason-ci-cd.apps.ae9d.example.opentlc.com
    port:
      targetPort: 443-https
    to:
      kind: Service
      name: gitlab
      weight: 100
    wildcardPolicy: None
  status:
    ingress:
    - conditions:
      - lastTransitionTime: 2018-06-26T20:14:55Z
        status: "True"
        type: Admitted
      host: gitlab-jason-ci-cd.apps.ae9d.example.opentlc.com
      routerName: router
      wildcardPolicy: None
